name: COPY DIST TO EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: create env
        run: |

          npm install
          npm run build
          echo "${{ secrets.DEV_ENV }}" >> .dev.env
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy dist folder to EC2
        run: |
          scp -r dist/ ec2-user@${{ secrets.REMOTE_IP }}:/home/ec2-user/dev/nestjs
          scp -r package.json ec2-user@${{ secrets.REMOTE_IP }}:/home/ec2-user/dev/nestjs
          scp -r node_modules ec2-user@${{ secrets.REMOTE_IP }}:/home/ec2-user/dev/nestjs
          scp -r package-lock.json ec2-user@${{ secrets.REMOTE_IP }}:/home/ec2-user/dev/nestjs

      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
